# Generated by Django 2.1.1 on 2018-09-13 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import inmediag.models
import simple_history.models
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('rfc', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='RFC')),
                ('domicilio', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['-creado'],
                'get_latest_by': 'creado',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('folio', models.CharField(default=inmediag.models.folio_generator, max_length=50, primary_key=True, serialize=False, verbose_name='Folio')),
                ('pendiente', models.BooleanField(default=True, verbose_name='Pendiente')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'diagnóstico',
                'verbose_name_plural': 'diagnósticos',
                'ordering': ['-folio'],
                'get_latest_by': 'folio',
            },
        ),
        migrations.CreateModel(
            name='Dictado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Texto')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('creado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dictado',
                'verbose_name_plural': 'dictados',
                'ordering': ['-creado'],
                'get_latest_by': 'creado',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('domicilio', models.TextField(blank=True, max_length=150, null=True)),
                ('celular', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_particular', models.CharField(blank=True, max_length=50, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'doctor',
                'verbose_name_plural': 'doctores',
                'ordering': ['-creado'],
                'get_latest_by': 'creado',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idestado', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'estado',
                'verbose_name_plural': 'estados',
            },
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=75, verbose_name='Descripción')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'estudio',
                'verbose_name_plural': 'estudios',
                'ordering': ['descripcion'],
                'get_latest_by': 'creado',
            },
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'firma',
                'verbose_name_plural': 'Firmas',
                'ordering': ['-creado'],
                'get_latest_by': 'creado',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCliente',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=150)),
                ('rfc', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='RFC')),
                ('domicilio', models.TextField()),
                ('creado', models.DateTimeField(blank=True, editable=False)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, editable=False, verbose_name='Última actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inmediag.Estado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical cliente',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDiagnostico',
            fields=[
                ('folio', models.CharField(db_index=True, default=inmediag.models.folio_generator, max_length=50, verbose_name='Folio')),
                ('pendiente', models.BooleanField(default=True, verbose_name='Pendiente')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico')),
                ('creado', models.DateTimeField(blank=True, editable=False)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, editable=False, verbose_name='Última actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dictado', smart_selects.db_fields.ChainedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inmediag.Dictado')),
                ('doctor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inmediag.Doctor')),
                ('estudio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inmediag.Estudio')),
                ('firma', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inmediag.Firma')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical diagnóstico',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDictado',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Texto')),
                ('creado', models.DateTimeField(blank=True, editable=False)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, editable=False, verbose_name='Última actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('estudio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inmediag.Estudio')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical dictado',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPaciente',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rfc', models.CharField(blank=True, default='Desconocido', max_length=30, null=True, verbose_name='ID')),
                ('creado', models.DateTimeField(blank=True, editable=False)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, editable=False, verbose_name='Última actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical paciente',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('idmunicipio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('idestado', models.ForeignKey(db_column='idestado', on_delete=django.db.models.deletion.CASCADE, to='inmediag.Estado')),
            ],
            options={
                'verbose_name': 'municipio',
                'verbose_name_plural': 'municipios',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rfc', models.CharField(blank=True, default='Desconocido', max_length=30, null=True, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'ordering': ['-creado'],
                'get_latest_by': 'creado',
            },
        ),
        migrations.AddField(
            model_name='historicaldiagnostico',
            name='paciente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inmediag.Paciente'),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inmediag.Municipio'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='pacientes',
            field=models.ManyToManyField(blank=True, db_table='inmediag_doctor_paciente', editable=False, to='inmediag.Paciente', verbose_name='Pacientes'),
        ),
        migrations.AddField(
            model_name='dictado',
            name='estudio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inmediag.Estudio'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='dictado',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='estudio', chained_model_field='estudio', null=True, on_delete=django.db.models.deletion.CASCADE, to='inmediag.Dictado'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inmediag.Doctor'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='estudio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inmediag.Estudio'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='firma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inmediag.Firma'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inmediag.Paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inmediag.Estado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='estado', chained_model_field='idestado', on_delete=django.db.models.deletion.CASCADE, to='inmediag.Municipio'),
        ),
    ]
